version: "3"

services:
  database:
    # build:
    #   context: ./client
    #   dockerfile: Dockerfile.dev
    image: mongo:latest
    container_name: backc
    volumes:
      - .:/data/db
    ports:
      - 27018:27017